// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;
import gov.wicourts.functest.CCAPTestScript;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>CloseLauncher</b><br>
 * Generated     : <b>2006/11/22 10:37:05 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 2000 x86 5.0 <br>
 * 
 * @since  November 22, 2006
 * @author agoodno
 */
public abstract class CloseLauncherHelper extends gov.wicourts.functest.CCAPTestScript
{
	/**
	 * JadeFrame: with default state.
	 *		.captionText : RegularExpression(.* County \- Court Applications \- .*)
	 * 		.class : gov.wicourts.jade.gui.JadeFrame
	 * 		accessibleContext.accessibleName : RegularExpression(.* County \- Court Applications \- .*)
	 */
	protected TopLevelTestObject jadeFrame() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("jadeFrame"));
	}
	/**
	 * JadeFrame: with specific test context and state.
	 *		.captionText : RegularExpression(.* County \- Court Applications \- .*)
	 * 		.class : gov.wicourts.jade.gui.JadeFrame
	 * 		accessibleContext.accessibleName : RegularExpression(.* County \- Court Applications \- .*)
	 */
	protected TopLevelTestObject jadeFrame(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("jadeFrame"), anchor, flags);
	}
	
	

	protected CloseLauncherHelper()
	{
		setScriptName("CloseLauncher");
	}
	
}