// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>DataBrowserExample</b><br>
 * Generated     : <b>2006/11/24 1:38:27 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 2000 x86 5.0 <br>
 * 
 * @since  November 24, 2006
 * @author agoodno
 */
public abstract class DataBrowserExampleHelper extends RationalTestScript
{
	

	protected DataBrowserExampleHelper()
	{
		setScriptName("DataBrowserExample");
	}
	
}