// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;
import gov.wicourts.functest.CCAPTestScript;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>VerifyAddEvent</b><br>
 * Generated     : <b>2006/11/27 1:11:32 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 2000 x86 5.0 <br>
 * 
 * @since  November 27, 2006
 * @author agoodno
 */
public abstract class VerifyAddEventHelper extends gov.wicourts.functest.CCAPTestScript
{
	/**
	 * Case: with default state.
	 *		.tabText : Case
	 * 		.class : us.wi.state.courts.jade.client.caseapp.Case
	 * 		name : CaseTP
	 */
	protected GuiTestObject _case() 
	{
		return new GuiTestObject(
                        getMappedTestObject("_case"));
	}
	/**
	 * Case: with specific test context and state.
	 *		.tabText : Case
	 * 		.class : us.wi.state.courts.jade.client.caseapp.Case
	 * 		name : CaseTP
	 */
	protected GuiTestObject _case(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("_case"), anchor, flags);
	}
	
	/**
	 * CaseAppFrame: with default state.
	 *		.captionText : RegularExpression(.* County \- Case Management \- .*)
	 * 		.class : us.wi.state.courts.jade.client.caseapp.CaseAF
	 * 		accessibleContext.accessibleName : RegularExpression(.* County \- Case Management \- .*)
	 * 		name : CaseAppFrame
	 */
	protected TopLevelTestObject caseAppFrame() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("caseAppFrame"));
	}
	/**
	 * CaseAppFrame: with specific test context and state.
	 *		.captionText : RegularExpression(.* County \- Case Management \- .*)
	 * 		.class : us.wi.state.courts.jade.client.caseapp.CaseAF
	 * 		accessibleContext.accessibleName : RegularExpression(.* County \- Case Management \- .*)
	 * 		name : CaseAppFrame
	 */
	protected TopLevelTestObject caseAppFrame(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("caseAppFrame"), anchor, flags);
	}
	
	/**
	 * CaseTabbedPane: with default state.
	 *		tabCount : 10
	 * 		.class : gov.wicourts.jade.gui.JadeTabbedPane
	 * 		.tabs : {Case,Parties,Citations,Charges,Assess,Receipts/Receivables,Judgments,Payables,D ...
	 * 		name : CaseTabbedPane
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject caseTabbedPane() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("caseTabbedPane"));
	}
	/**
	 * CaseTabbedPane: with specific test context and state.
	 *		tabCount : 10
	 * 		.class : gov.wicourts.jade.gui.JadeTabbedPane
	 * 		.tabs : {Case,Parties,Citations,Charges,Assess,Receipts/Receivables,Judgments,Payables,D ...
	 * 		name : CaseTabbedPane
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject caseTabbedPane(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("caseTabbedPane"), anchor, flags);
	}
	
	/**
	 * courtRecordJTP: with default state.
	 *		.class : gov.wicourts.jade.gui.JadeTable
	 * 		.priorLabel : Branch:
	 * 		name : courtRecordJTP
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject courtRecordJTP() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("courtRecordJTP"));
	}
	/**
	 * courtRecordJTP: with specific test context and state.
	 *		.class : gov.wicourts.jade.gui.JadeTable
	 * 		.priorLabel : Branch:
	 * 		name : courtRecordJTP
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject courtRecordJTP(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("courtRecordJTP"), anchor, flags);
	}
	
	/**
	 * InquiryCase: with default state.
	 *		.class : gov.wicourts.jade.gui.JadeInternalFrame
	 * 		accessibleContext.accessibleName : RegularExpression(Inquiry \- Case\: [a-zA-Z0-9])
	 * 		title : RegularExpression(Inquiry \- Case\: [a-zA-Z0-9])
	 */
	protected InternalFrameTestObject inquiryCase() 
	{
		return new InternalFrameTestObject(
                        getMappedTestObject("inquiryCase"));
	}
	/**
	 * InquiryCase: with specific test context and state.
	 *		.class : gov.wicourts.jade.gui.JadeInternalFrame
	 * 		accessibleContext.accessibleName : RegularExpression(Inquiry \- Case\: [a-zA-Z0-9])
	 * 		title : RegularExpression(Inquiry \- Case\: [a-zA-Z0-9])
	 */
	protected InternalFrameTestObject inquiryCase(TestObject anchor, long flags) 
	{
		return new InternalFrameTestObject(
                        getMappedTestObject("inquiryCase"), anchor, flags);
	}
	
	/**
	 * JScrollPane: with default state.
	 *		.class : javax.swing.JScrollPane
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject jScrollPane() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("jScrollPane"));
	}
	/**
	 * JScrollPane: with specific test context and state.
	 *		.class : javax.swing.JScrollPane
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject jScrollPane(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("jScrollPane"), anchor, flags);
	}
	
	/**
	 * JadeDialog: with default state.
	 *		.captionText : New - Case Selection
	 * 		.class : gov.wicourts.jade.gui.JadeDialog
	 */
	protected TopLevelTestObject jadeDialog() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("jadeDialog"));
	}
	/**
	 * JadeDialog: with specific test context and state.
	 *		.captionText : New - Case Selection
	 * 		.class : gov.wicourts.jade.gui.JadeDialog
	 */
	protected TopLevelTestObject jadeDialog(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("jadeDialog"), anchor, flags);
	}
	
	/**
	 * JadeMenuBar: with default state.
	 *		.class : gov.wicourts.jade.gui.JadeMenuBar
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject jadeMenuBar() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("jadeMenuBar"));
	}
	/**
	 * JadeMenuBar: with specific test context and state.
	 *		.class : gov.wicourts.jade.gui.JadeMenuBar
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject jadeMenuBar(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("jadeMenuBar"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point courtRecordJTP_selected object in the SUT.
	 */
	protected IFtVerificationPoint courtRecordJTP_selectedVP() 
	{
		return vp("courtRecordJTP_selected");
	}
	protected IFtVerificationPoint courtRecordJTP_selectedVP(TestObject anchor)
	{
		return vp("courtRecordJTP_selected", anchor);
	}
	
	

	protected VerifyAddEventHelper()
	{
		setScriptName("VerifyAddEvent");
	}
	
}